### ISSUE TITLE
Need to collect data from the ingress-nginx namespace

### ISSUE THREAD

**Issue by mkolinsk** [ibm-apiconnect/v2018-postmortem#9]
we need to collect the same data on the `ingress-nginx` namespace as we do for `kube-system` and the apic namespace. I have frequently seen the ingress controller in the `ingress-nginx`namespace when deployed on AWS/EKS and with the current version of postmortem tool we don't get the data we need.

**Comment by nitekon1** [comment]
Added in commit 37eaf1e.

From this article:
https://aws.amazon.com/blogs/opensource/network-load-balancer-nginx-ingress-controller-eks/

appears AWS suggest using `kubectl` (instead of `helm`) to deploy the **ingress-nginx** controller.

Now if `helm ls` output does not contain `nginx-ingress` will check all namespaces for `nginx-ingress` recording where found.
